from .packet import Packet

class Header:
    V00 = bytes('V00', Packet.ENCODING)
    V70 = bytes('V70', Packet.ENCODING)
    Y00 = bytes('Y00', Packet.ENCODING)
    F00 = bytes('F00', Packet.ENCODING)
    T00 = bytes('T00', Packet.ENCODING)
    T10 = bytes('T10', Packet.ENCODING)
    P00 = bytes('P00', Packet.ENCODING)
    P01 = bytes('P01', Packet.ENCODING)
    U10 = bytes('U10', Packet.ENCODING)
    Z00 = bytes('Z00', Packet.ENCODING)
    S00 = bytes('S00', Packet.ENCODING)
    S01 = bytes('S01', Packet.ENCODING)
    S02 = bytes('S02', Packet.ENCODING)
    S03 = bytes('S03', Packet.ENCODING)
    S04 = bytes('S04', Packet.ENCODING)
    A00 = bytes('A00', Packet.ENCODING)
    A01 = bytes('A01', Packet.ENCODING)
    D00 = bytes('D00', Packet.ENCODING)
    E00 = bytes('E00', Packet.ENCODING)
    E01 = bytes('E01', Packet.ENCODING)
    X00 = bytes('X00', Packet.ENCODING)
    X70 = bytes('X70', Packet.ENCODING)
    I00 = bytes('I00', Packet.ENCODING)
    S20 = bytes('S20', Packet.ENCODING)
    S21 = bytes('S21', Packet.ENCODING)
    S22 = bytes('S22', Packet.ENCODING)
    S23 = bytes('S23', Packet.ENCODING)
    L70 = bytes('L70', Packet.ENCODING)
    M70 = bytes('M70', Packet.ENCODING)
    M71 = bytes('M71', Packet.ENCODING)
    M72 = bytes('M72', Packet.ENCODING)

